FROM eclipse-temurin:17-jre-focal
LABEL maintainer="dlmcpaul@gmail.com"

ARG JAR_FILE
COPY ${JAR_FILE} /app.jar

RUN <<EOF
#!/bin/sh
if [ -f "/internal_db/solar_stats_db.mv.db" ]; then
  echo "V1 of H2 database found running upgrade"

  # Download migration tool
  curl -Lo H2MigrationTool.jar https://github.com/manticore-projects/H2MigrationTool/releases/download/1.2/H2MigrationTool-all.jar

  # rename as a backup file
  mv /internal_db/solar_stats_db.mv.db /internal_db/solar_stats_db_v1.mv.db

  # convert database
  echo "Converting H2 database to V2"
  java -jar H2MigrationTool-all.jar -f 1.4.200 -t 2.1.210 -d /internal_db/solar_stats_db_v1.mv.db

  #rename converted file to new database name
  mv /internal_db/solar_stats_db_v1.210null.mv.db /internal_db/solar_stats_db_v2.mv.db

  echo "Upgrade completed"
fi
EOF

ENV SPRING_DATASOURCE_URL=jdbc:h2:/internal_db/solar_stats_db_v2
RUN mkdir "/properties" && \
    touch "/properties/application.properties"

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.jmx.enabled=false", "-jar", "app.jar", "--spring.config.additional-location=file:/properties/application.properties"]

EXPOSE 8080

VOLUME /internal_db /properties