FROM alpine:3.8 as builder
MAINTAINER David McPaul <dlmcpaul@gmail.com>

# Generate a minimal java runtime using the latest Portola distribution
# MODULES should contain the ouput from jdeps --list-deps ${JAR_FILE}
# maybe use 'export MODULES=$(jdeps --list-deps ${JAR_FILE})'
ARG MODULES
ARG JAR_FILE
RUN mkdir -p /opt/jdk \
     && cd /opt/jdk \
     && wget -O openjdk-musl.tar.gz https://download.java.net/java/early_access/alpine/25/binaries/openjdk-12-ea+25_linux-x64-musl_bin.tar.gz \
     && tar -zxvf openjdk-musl.tar.gz \
     && rm openjdk-musl.tar.gz \
     && ./jdk-12/bin/jlink \
    --add-modules  \
    ${MODULES},java.xml,jdk.unsupported,java.sql,java.naming,java.desktop,java.management,java.security.jgss,java.instrument \
    --verbose \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /opt/jre-minimal

# Start with fresh copy of alpine linux
FROM alpine:3.8

# copy our minimal runtime
RUN mkdir -p /opt/app
COPY --from=builder /opt/jre-minimal /opt/jdk

# copy our application
ADD ${JAR_FILE} /opt/app/enphasecollector.jar

# expose the internal actuator endpoints
EXPOSE 8080

CMD ["/opt/jdk/bin/java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/opt/app/enphasecollector.jar"]