
ALTER TABLE EVENT ADD COLUMN GRID DECIMAL(19,2) AFTER VOLTAGE;
ALTER TABLE EVENT ADD COLUMN PERCENT_FULL DECIMAL(19, 2) AFTER GRID;
ALTER TABLE EVENT ADD COLUMN CHARGE_STATE CHARACTER VARYING(10) AFTER PERCENT_FULL;
ALTER TABLE EVENT ADD COLUMN BATTERY_WATTS DECIMAL(19, 2) AFTER CHARGE_STATE;
ALTER TABLE EVENT ADD COLUMN BATTERY_POWER DECIMAL(19,2) AFTER BATTERY_WATTS;
ALTER TABLE EVENT ADD COLUMN BATTERY_CELL_TEMPERATURE DECIMAL(19,2) AFTER BATTERY_POWER;

ALTER TABLE SUMMARY ADD COLUMN BATTERY_MIN_PERCENT DECIMAL(19, 2) AFTER CONVERSION_RATE;
ALTER TABLE SUMMARY ADD COLUMN BATTERY_MAX_PERCENT DECIMAL(19, 2) AFTER BATTERY_MIN_PERCENT;
ALTER TABLE SUMMARY ADD COLUMN BATTERY_CHARGED DECIMAL(19,2) AFTER BATTERY_MAX_PERCENT;
ALTER TABLE SUMMARY ADD COLUMN BATTERY_DISCHARGED DECIMAL(19,2) AFTER BATTERY_CHARGED;
ALTER TABLE SUMMARY ADD COLUMN BATTERY_MAX_CELL_TEMPERATURE DECIMAL(19,2) AFTER BATTERY_DISCHARGED;